US-022
viktor-debre/LawyerTimeTracker pull request #20
Opened 2022-06-07 14:33 UTC by SofaDeveloper

2022-06-08 14:02 UTC, viktor-debre commented on Controllers/AccountController.cs
> +                .FirstOrDefaultAsync(userInDatabase => userInDatabase.Email == User.Identity.Name);
I think it can be put in a separate service. When you resolve this Ishenko Alexey please tell me because we need the same service in TaskController.

2022-06-08 14:29 UTC, viktor-debre requested changes

2022-06-08 14:29 UTC, viktor-debre commented on Views/Home/ViewUsers.cshtml
> +        string lastName = String.IsNullOrEmpty(item.LastName) ? "<Не указано>" : item.LastName;
When you change fields first name and last name to not null type this checkup will be redundant.

2022-06-08 14:29 UTC, viktor-debre commented on Views/Shared/_Layout.cshtml
> +                </div>
When you openind this section all Layout is also opening, I consider here should be something like just combo box
![image](https://user-images.githubusercontent.com/95490580/172641799-c14863dd-b8df-456b-9e52-e6685329f4a6.png)

2022-06-11 17:36 UTC, viktor-debre approved these changes

2022-06-12 07:40 UTC, KapNelson approved these changes

2022-06-12 07:40 UTC, merged