[US-011] Add add-update-delete options
viktor-debre/LawyerTimeTracker pull request #25
Opened 2022-06-13 14:40 UTC by viktor-debre

2022-06-13 14:48 UTC, KapNelson requested changes

2022-06-13 14:48 UTC, KapNelson commented on Controllers/TaskController.cs
> +        }
The controller should contain only methods that mapping some kind of request

2022-06-13 14:48 UTC, KapNelson commented on Models/ViewModels/NewTaskModel.cs
> +}
Minor: perhaps we can somehow reuse an existing model?

2022-06-13 14:48 UTC, KapNelson commented on Views/Task/Issues.cshtml
> +    Issue updatingIssue = new Issue();
Where are you using this variable?

2022-06-13 14:51 UTC, viktor-debre commented on Models/ViewModels/NewTaskModel.cs
> +}
It's true but then we need to move validation to javascript, in the future, we can do that.

2022-06-13 15:05 UTC, viktor-debre commented on Views/Task/Issues.cshtml
> +    Issue updatingIssue = new Issue();
Yes, it is redundant, i removed it.

2022-06-14 06:58 UTC, SofaDeveloper commented on Controllers/TaskController.cs
> +        }
I think we can combine this logic into 1 method.

2022-06-14 07:37 UTC, SofaDeveloper requested changes

2022-06-14 07:37 UTC, SofaDeveloper commented on Controllers/TaskController.cs
> +            await _taskService.UpdateTask(currentIssue);
This logic should be in service

2022-06-14 07:38 UTC, SofaDeveloper requested changes

2022-06-14 07:38 UTC, SofaDeveloper commented on Controllers/TaskController.cs
> +        }
This logic (86-90 lines) should be in service

2022-06-14 13:27 UTC, SofaDeveloper approved these changes

2022-06-15 06:27 UTC, KapNelson approved these changes

2022-06-15 06:28 UTC, merged