Task-005
viktor-debre/LawyerTimeTracker pull request #9
Opened 2022-04-27 16:26 UTC by viktor-debre

Created connection to database in project. 
Installed Pomelo.EntityFramework.MySql by NuGet.
Create simple form for adding and viewing users.

2022-04-29 14:49 UTC, KapNelson requested changes
Reply to all comments

2022-04-29 14:49 UTC, KapNelson commented on Controllers/HomeController.cs
> +        private ApplicationContext db;
Explain why you chose this particular variable name? I think it is not entirely correct, in terms of compliance with the real purpose.

2022-04-29 16:34 UTC, viktor-debre commented on Controllers/HomeController.cs
> +        private ApplicationContext db;
Thank you for the advice, this name is really inappropriate in this situation. It has been already changed to databaseContext, which is easier to understand.

2022-04-30 08:55 UTC, viktor-debre commented on appsettings.Development.json
> +    "MariaDbConnectionString": "server=localhost;port=3306;user id=root;password=tatoserg4;database=lawyer_db"
Added as another task on canbas board.

2022-04-30 08:56 UTC, merged